"""
English descriptions for attack patterns.
Used when bot_lang = 'en'. LT descriptions remain in correlator.py ATTACK_PATTERNS.
"""

PATTERN_DESC_EN = {
    "ACCESSIBILITY_BACKDOOR":   "Accessibility feature backdoor (Sticky Keys / Utilman)",
    "ACTIVE_SETUP_PERSIST":     "Active Setup registry persistence",
    "ADCS_ABUSE":               "Active Directory Certificate Services abuse",
    "AD_RECON":                 "Active Directory reconnaissance",
    "AI_AGENT_COMPROMISE":      "AI agent / MCP server compromise for code execution",
    "AI_TOOL_ABUSE":            "AI tool abuse for attacks (prompt injection / jailbreak)",
    "AMSI_BYPASS":              "AMSI/ETW protection bypass",
    "ANYCONNECT_EXPLOIT":       "Cisco ASA / AnyConnect / IOS CVE exploitation",
    "APPLOCKER_BYPASS":         "AppLocker / WDAC protection bypass",
    "AS_REP_ROASTING":          "AS-REP Roasting — accounts without Kerberos pre-auth",
    "AV_KILL":                  "AV/EDR process and service termination",
    "AWS_ABUSE":                "AWS IAM / credentials abuse",
    "AZURE_ABUSE":              "Azure AD / M365 post-compromise abuse",
    "AZURE_ARC_ABUSE":          "Azure Arc hybrid agent abuse for code execution",
    "BITM_ATTACK":              "Browser-in-the-Middle (BitM) — real-time session hijack",
    "BITS_ABUSE":               "BITS job abuse (download + persistence)",
    "BLACKCAT_ALPHV_TTP":       "BlackCat/ALPHV ransomware operator TTPs",
    "BRING_YOUR_OWN_DRIVER":    "BYOD — vulnerable driver used for kernel access",
    "BROWSER_CRED_THEFT":       "Browser credential theft",
    "CHM_SCRIPTLET":            "CHM / Scriptlet / HTA malicious execution",
    "CITRIX_EXPLOIT":           "Citrix / NetScaler CVE exploitation",
    "CLOUD_RECON":              "Cloud/SaaS infrastructure reconnaissance",
    "COBALT_STRIKE_INDICATORS": "Cobalt Strike infrastructure indicators",
    "COM_HIJACK":               "COM object hijacking (persistence / UAC bypass)",
    "CONFLUENCE_EXPLOIT":       "Atlassian Confluence RCE exploitation",
    "CONTAINER_ESCAPE":         "Container isolation escape",
    "CREDENTIAL_DUMP":          "Credential extraction from LSASS/SAM/NTDS",
    "CREDENTIAL_FILE_ACCESS":   "Access to credential file locations",
    "CRON_DOWNLOAD_EXEC":       "Cron job downloads and executes code from internet",
    "CRYPTOMINING":             "Cryptocurrency mining software",
    "DATA_EXFIL":               "Data exfiltration to external server",
    "DCOM_LATERAL":             "DCOM objects used for lateral movement",
    "DCSHADOW":                 "DCShadow — rogue domain controller replication injection",
    "DCSYNC":                   "DCSync attack — domain credential replication",
    "DEEPFAKE_VISHING":         "Deepfake voice/video social engineering (BEC 2.0)",
    "DEFENSE_EVASION":          "Defense evasion / security control disabling",
    "DIAMOND_TICKET":           "Diamond Ticket — Kerberos TGT forgery without krbtgt change",
    "DISK_ENCRYPTION_PREP":     "Disk / MBR encryption preparation",
    "DLL_SIDELOAD":             "DLL side-loading / hijacking via trusted application",
    "DNS_EXFIL":                "DNS tunnel-based data exfiltration / C2",
    "DOCKER_SOCKET_ABUSE":      "Docker socket abuse for privilege escalation",
    "DPAPI_ABUSE":              "DPAPI secret data extraction",
    "EMAIL_COLLECTION":         "Email / Exchange data collection",
    "ENTRA_ID_ABUSE":           "Microsoft Entra ID (Azure AD) advanced abuse",
    "ESXI_ATTACK":              "VMware ESXi server targeting (ransomware / persistence)",
    "ETW_PATCH":                "ETW / NT API hook removal (syscall patching)",
    "EXCHANGE_ABUSE":           "Microsoft Exchange server exploit / abuse",
    "FIRMWARE_PERSIST":         "UEFI / Firmware level persistence (APT grade)",
    "FORTINET_EXPLOIT":         "FortiGate / FortiOS CVE exploitation",
    "GITHUB_ACTIONS_ABUSE":     "CI/CD pipeline abuse (GitHub Actions / Jenkins)",
    "GOLDEN_SILVER_TICKET":     "Golden / Silver Ticket Kerberos ticket forgery",
    "GPO_ABUSE":                "Group Policy abuse (persistence / lateral movement)",
    "HNDL_COLLECTION":          "Harvest Now Decrypt Later — encrypted traffic collection",
    "HTML_SMUGGLING":           "HTML Smuggling — payload delivery via browser",
    "ICMP_COVERT":              "ICMP / protocol tunneling for covert data transfer",
    "ICS_OT_RECON":             "ICS / SCADA / OT systems reconnaissance",
    "ICS_PROTOCOL_ABUSE":       "ICS protocol abuse (Modbus / DNP3 / S7)",
    "IMDS_ABUSE":               "Cloud instance metadata service abuse (SSRF→IMDS)",
    "INTERNAL_SPEARPHISH":      "Internal spearphishing — sent from compromised user",
    "ISO_LNK_EXEC":             "ISO/IMG/ZIP + LNK file execution (Mark-of-the-Web bypass)",
    "KERBEROASTING":            "Kerberoasting — SPN ticket harvesting",
    "KERBEROS_DELEGATION":      "Kerberos delegation abuse (unconstrained/RBCD)",
    "KERNEL_CALLBACK_REMOVAL":  "Windows kernel callback removal for EDR bypass",
    "KEYLOGGING":               "Keyboard keystroke logging",
    "LAPS_ABUSE":               "LAPS (Local Admin Password Solution) password reading",
    "LATERAL_MOVEMENT":         "Lateral movement across network",
    "LAZARUS_TTP":              "Lazarus Group (DPRK) — financial sector targeting",
    "LINUX_CAPABILITY_ABUSE":   "Linux capabilities abuse for privilege escalation",
    "LINUX_CRED_DUMP":          "Linux password / credential extraction",
    "LINUX_EBPF_ABUSE":         "eBPF rootkit / stealthy monitoring",
    "LINUX_LD_PRELOAD":         "LD_PRELOAD injection (persistence / privilege escalation)",
    "LINUX_MEMFD_EXEC":         "In-memory execution (fileless Linux)",
    "LINUX_PERSISTENCE":        "Linux persistence mechanisms",
    "LINUX_PRIVESC":            "Linux privilege escalation",
    "LINUX_PROC_INJECTION":     "Linux process injection via ptrace / /proc",
    "LINUX_RECON":              "Linux system reconnaissance post-compromise",
    "LINUX_ROOTKIT":            "Linux kernel rootkit / malicious module loading",
    "LINUX_SSH_ABUSE":          "Linux SSH key theft / modification / tunneling",
    "LIVING_OFF_THE_LAND_PS":   "PowerShell LOLBin attack chain",
    "LIVING_OFF_TRUSTED_SITES": "Trusted sites used for C2 / data exfiltration (LOTS)",
    "LLMNR_POISONING":          "LLMNR/NBT-NS/mDNS poisoning",
    "LOG_CLEARING":             "Event log clearing",
    "LOLBIN_EXEC":              "LOLBin file download and execution",
    "LSASS_COMSVCS":            "LSASS dump via comsvcs.dll / Task Manager",
    "LSASS_PPL_BYPASS":         "LSASS PPL protection bypass",
    "LSA_PROVIDER_PERSIST":     "LSA Security Package / Authentication Package persistence",
    "MASQUERADE_PROC":          "Process masquerading (system name impersonation)",
    "MEMORY_ONLY_STAGE":        "Fully fileless attack chain (no file on disk)",
    "MFA_BYPASS":               "MFA/SSO bypass",
    "MFA_FATIGUE_ADVANCED":     "Advanced MFA fatigue + social engineering combination",
    "MICROSOFT_TEAMS_PHISH":    "Microsoft Teams phishing / malware delivery",
    "MOVEIT_EXPLOIT":           "MOVEit Transfer (CVE-2023-34362) exploitation",
    "NETSH_HELPER_DLL":         "Netsh helper DLL persistence",
    "NETWORK_SNIFF":            "Network traffic sniffing / ARP spoofing",
    "NHI_CREDENTIAL_ABUSE":     "Non-Human Identity (service accounts / API keys) abuse",
    "NTDS_EXTRACTION":          "NTDS.dit domain database extraction",
    "NTLM_COERCION":            "NTLM authentication coercion (for relay attacks)",
    "OAUTH_ABUSE":              "OAuth Device Code Flow / consent grant phishing",
    "OBFUSCATION_INDICATORS":   "Code obfuscation indicators",
    "OFFICE_ADDIN_PERSIST":     "Office Add-in / Template persistence",
    "OFFICE_MACRO_CHAIN":       "Office document macro spawned child process",
    "OVERPASS_THE_HASH":        "Overpass-the-Hash — NT hash → Kerberos TGT",
    "PASSKEY_BYPASS":           "Passkey / FIDO2 bypass via session hijacking",
    "PASSWORD_POLICY_ENUM":     "Password policy / Kerberos settings reconnaissance",
    "PASS_CERTIFICATE":         "Pass-the-Certificate (PKINIT) — certificate-based auth",
    "PASS_THE_HASH":            "Pass-the-Hash / Pass-the-Ticket authentication",
    "PASS_THE_TICKET":          "Pass-the-Ticket — Kerberos ticket relay",
    "PERSISTENCE_SETUP":        "Persistence mechanism installation",
    "PHANTOM_DLL_HOLLOW":       "Phantom DLL hollowing — non-existent module injection",
    "PORT_FORWARD":             "Port forwarding / pivot via compromised machine",
    "POWER_PLATFORM_ABUSE":     "Microsoft Power Platform / Power Automate abuse",
    "PPID_SPOOF":               "Parent process ID spoofing (PPID Spoofing)",
    "PRINT_NIGHTMARE":          "PrintNightmare (CVE-2021-34527) printer driver exploit",
    "PRIVESC_TOOLS":            "Privilege escalation tools",
    "PROCESS_INJECTION":        "Process injection / hollowing",
    "PROMPT_INJECTION_RCE":     "Prompt injection → code execution via LLM integration",
    "PROXY_MULTIHOP":           "Multi-hop proxy chain for C2 communication",
    "PS_NETWORK_SCAN":          "PowerShell internal network scan (ping sweep / host discovery)",
    "PS_PROCESS_DISCOVERY":     "PowerShell process/system discovery — reconnaissance",
    "QUISHING":                 "QR code phishing → credential harvest / malware",
    "RANSOMWARE_ENCRYPTION":    "Active file encryption phase indicators",
    "RANSOMWARE_PRELUDE":       "Ransomware prelude — backup destruction",
    "RDP_ABUSE":                "Unusual RDP usage / lateral movement via RDP",
    "RECON_CHAIN":              "Reconnaissance command chain",
    "REFLECTIVE_LOAD":          "Reflective DLL/Assembly loading (fileless execution)",
    "REGISTRY_DEEP_PERSISTENCE":"Deep registry persistence locations",
    "RMM_ABUSE":                "Remote Management Tool abuse (AnyDesk/TeamViewer/ScreenConnect)",
    "RUST_GO_MALWARE":          "Rust / Go language malware (EDR evasion)",
    "SAFE_MODE_EVASION":        "Safe mode boot for AV evasion (ransomware TTP)",
    "SAM_HIVE_DUMP":            "SAM/SYSTEM/SECURITY registry memory extraction",
    "SCATTERED_SPIDER_TTP":     "Scattered Spider (UNC3944) — SIM swap + MFA + RMM",
    "SCREENSAVER_PERSIST":      "Screensaver persistence",
    "SCREEN_CAPTURE":           "Screen / keyboard / clipboard data collection",
    "SECURITY_TOOL_ENUM":       "AV / EDR / security tool enumeration",
    "SEO_POISONING_EXEC":       "SEO poisoning / malvertising delivery execution chain",
    "SERVICE_BULK_STOP":        "Bulk service termination (ransomware / wiper prelude)",
    "SHADOW_CREDENTIALS":       "msDS-KeyCredentialLink manipulation (Shadow Credentials)",
    "SHARE_ENUM_COLLECTION":    "Network share enumeration and file collection",
    "SKELETON_KEY":             "Skeleton Key — domain controller authentication backdoor",
    "SLOPSQUATTING":            "AI hallucination package name exploitation (typosquatting 2.0)",
    "STARTUP_PERSISTENCE":      "Startup folder persistence",
    "SUPPLY_CHAIN_INDICATORS":  "Supply chain attack indicators",
    "TIMESTOMPING":             "File timestamp metadata manipulation",
    "TOKEN_MANIPULATION":       "Token theft / process impersonation",
    "TPM_SNIFF":                "TPM bus sniffing for BitLocker key extraction",
    "TUNNELING":                "Network tunnel creation (C2 / data exfiltration)",
    "USER_ACCOUNT_MANIP":       "User account manipulation",
    "VDSO_INJECTION":           "vDSO / vsyscall injection (Linux kernel evasion)",
    "VM_SANDBOX_DETECT":        "Virtual machine / sandbox environment detection",
    "VOLT_TYPHOON_TTP":         "Volt Typhoon (APT41-CN) — heavy LOLBins, zero footprint",
    "WIFI_ATTACK":              "Wi-Fi network attack / eavesdropping",
    "WINDOWS_DEFENDER_EXCL":    "Windows Defender exclusion added for malicious content",
    "WINDOWS_HELLO_BYPASS":     "Windows Hello biometric authentication bypass",
    "WINRM_LATERAL":            "WinRM-based lateral movement",
    "WIPER_INDICATORS":         "Data destruction / wiper indicators",
    "WMI_PERSISTENCE":          "WMI event subscription persistence",
    "WSUS_ATTACK":              "WSUS server attack — malicious update distribution",
    "ZEROLOGON":                "Zerologon (CVE-2020-1472) domain controller compromise",
    # Behavioral / new signals
    "NETWORK_SCAN_BEHAVIOR":    "Behavioral network scan — process connected to >15 unique targets in 3min",
    "PROCESS_RECON_CHAIN":      "Recon process chain — parent spawned 4+ discovery tools in 90sec",
    "SUSPICIOUS_SERVICE":       "Suspicious Windows service name (threat intel list)",
    "SUSPICIOUS_NAMED_PIPE":    "Suspicious named pipe — possible C2/RAT (threat intel list)",
}


def get_pattern_desc(name: str, lang: str) -> str:
    """Return pattern description in the requested language."""
    if lang == "en":
        return PATTERN_DESC_EN.get(name, name)
    # LT — grąžiname None, kad correlator naudotų savo desc lauką
    return None
