CREATE TABLE IF NOT EXISTS response_playbooks (
    id               BIGSERIAL PRIMARY KEY,
    trigger_type     TEXT NOT NULL UNIQUE,   -- chain/signal/pattern tipas
    description      TEXT,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    auto_isolate     BOOLEAN NOT NULL DEFAULT FALSE,
    notify_telegram  BOOLEAN NOT NULL DEFAULT TRUE,
    min_severity     SMALLINT NOT NULL DEFAULT 10,
    cooldown_minutes INTEGER  NOT NULL DEFAULT 30,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_by       TEXT DEFAULT 'system'
);
CREATE INDEX IF NOT EXISTS idx_playbooks_trigger ON response_playbooks(trigger_type);
CREATE INDEX IF NOT EXISTS idx_playbooks_enabled  ON response_playbooks(enabled);

-- ── Default playbook įrašai ───────────────────────────────────────────────────
-- Grupės pagal auto_isolate politiką:
--   KRITINIAI  (score 90-95): auto_isolate=TRUE,  min_severity=11
--   AUKŠTI     (score 70-89): auto_isolate=TRUE,  min_severity=12
--   VIDUTINIAI (score 50-69): auto_isolate=FALSE, min_severity=13 (tik pranešimas)
--   ŽEMI       (score <50):   auto_isolate=FALSE, tik Telegram

INSERT INTO response_playbooks (trigger_type, description, auto_isolate, notify_telegram, min_severity, cooldown_minutes) VALUES

-- ── KRITINIAI — automatinė izoliacija nuo severity 11 ─────────────────────
('RANSOMWARE_ENCRYPTION',  'Aktyvus failų šifravimas — nedelsiamas atsakas',              TRUE,  TRUE, 11, 0),
('WIPER_INDICATORS',       'Duomenų naikinimas — nedelsiamas atsakas',                     TRUE,  TRUE, 11, 0),
('FIRMWARE_PERSIST',       'UEFI/Firmware rootkit — kritinis kompromisas',                 TRUE,  TRUE, 11, 0),
('SKELETON_KEY',           'Skeleton Key — DC kompromisas',                                TRUE,  TRUE, 11, 0),
('ZEROLOGON',              'Zerologon CVE-2020-1472 — DC perėmimas',                       TRUE,  TRUE, 11, 0),
('ICS_PROTOCOL_ABUSE',     'ICS/SCADA protokolų manipuliacija — fizinis pavojus',          TRUE,  TRUE, 11, 0),
('RANSOMWARE_PRELUDE',     'Ransomware preliudija (VSS+BCDedit) — izoliuoti prieš šifr.', TRUE,  TRUE, 11, 5),
('DCSYNC',                 'DCSync — domeno kredencialų ištraukimas',                      TRUE,  TRUE, 11, 10),
('DCSHADOW',               'DCShadow — klaidingų replikacijų injekcija',                   TRUE,  TRUE, 11, 10),
('NTDS_EXTRACTION',        'NTDS.dit ištraukimas — visi domeno kredencialai',              TRUE,  TRUE, 11, 10),
('DISK_ENCRYPTION_PREP',   'MBR/disko šifravimo paruošimas',                               TRUE,  TRUE, 11, 0),
('LOG4SHELL',              'Log4Shell RCE exploit',                                         TRUE,  TRUE, 11, 15),
('MOVEIT_EXPLOIT',         'MOVEit Transfer exploitation',                                  TRUE,  TRUE, 11, 15),
('CONFLUENCE_EXPLOIT',     'Confluence RCE exploitation',                                   TRUE,  TRUE, 11, 15),
('EXCHANGE_ABUSE',         'Exchange ProxyLogon/ProxyShell exploit',                        TRUE,  TRUE, 11, 15),

-- ── AUKŠTI — automatinė izoliacija nuo severity 12 ───────────────────────
('CREDENTIAL_DUMP',        'LSASS/SAM/NTDS kredencialų ištraukimas',                       TRUE,  TRUE, 12, 15),
('LSASS_COMSVCS',          'LSASS dump per comsvcs.dll',                                   TRUE,  TRUE, 12, 15),
('LSASS_PPL_BYPASS',       'LSASS PPL apsaugos aplenkimas',                                TRUE,  TRUE, 12, 15),
('GOLDEN_SILVER_TICKET',   'Kerberos bilietų klastojimas',                                 TRUE,  TRUE, 12, 15),
('DIAMOND_TICKET',         'Diamond ticket Kerberos',                                       TRUE,  TRUE, 12, 15),
('PASS_THE_HASH',          'Pass-the-Hash autentifikacija',                                 TRUE,  TRUE, 12, 20),
('PASS_THE_TICKET',        'Pass-the-Ticket Kerberos',                                     TRUE,  TRUE, 12, 20),
('PASS_CERTIFICATE',       'Pass-the-Certificate PKINIT',                                   TRUE,  TRUE, 12, 20),
('SAM_HIVE_DUMP',          'SAM/SYSTEM registry dump',                                     TRUE,  TRUE, 12, 15),
('WIN_LSASS_DUMP',         'Sysmon LSASS process access',                                  TRUE,  TRUE, 12, 15),
('C2_FRAMEWORK',           'Žinomas C2 framework aptiktas',                                TRUE,  TRUE, 12, 20),
('COBALT_STRIKE_INDICATORS','Cobalt Strike indikatoriai',                                  TRUE,  TRUE, 12, 20),
('KERNEL_CALLBACK_REMOVAL','Kernel callback šalinimas — EDR neutralizacija',               TRUE,  TRUE, 12, 15),
('BRING_YOUR_OWN_DRIVER',  'BYOVD kernel exploit',                                         TRUE,  TRUE, 12, 15),
('ESXI_ATTACK',            'VMware ESXi taikymas',                                          TRUE,  TRUE, 12, 15),
('SERVICE_BULK_STOP',      'Masinis paslaugų stabdymas',                                   TRUE,  TRUE, 12, 10),
('AV_KILL',                'AV/EDR procesų stabdymas',                                     TRUE,  TRUE, 12, 10),
('SAFE_MODE_EVASION',      'Saugaus režimo įjungimas ransomware tikslais',                 TRUE,  TRUE, 12, 10),
('WIN_UNSIGNED_DRIVER',    'Nepasirašyta tvarkyklė įkelta',                                TRUE,  TRUE, 12, 20),
('DOCKER_SOCKET_ABUSE',    'Docker socket privilege escalation',                            TRUE,  TRUE, 12, 15),
('K8S_ABUSE',              'Kubernetes RBAC/pod abuse',                                     TRUE,  TRUE, 12, 15),
('CITRIX_EXPLOIT',         'Citrix/NetScaler CVE exploitation',                             TRUE,  TRUE, 12, 15),
('FORTINET_EXPLOIT',       'FortiGate/FortiOS CVE exploitation',                            TRUE,  TRUE, 12, 15),
('ANYCONNECT_EXPLOIT',     'Cisco ASA/AnyConnect exploitation',                             TRUE,  TRUE, 12, 15),
('PASSKEY_BYPASS',         'Passkey/FIDO2 aplenkimas',                                     TRUE,  TRUE, 12, 20),
('BITM_ATTACK',            'Browser-in-the-Middle sesijos perėmimas',                      TRUE,  TRUE, 12, 20),
('ENTRA_ID_ABUSE',         'Entra ID PRT vagystė',                                         TRUE,  TRUE, 12, 20),
('LINUX_ROOTKIT',          'Linux kernel rootkit įkėlimas',                                TRUE,  TRUE, 12, 15),
('LINUX_EBPF_ABUSE',       'eBPF rootkit/stealthinis monitoringas',                        TRUE,  TRUE, 12, 15),
('LINUX_SSH_BRUTE_SUCCESS','SSH brute force sėkmingas prisijungimas',                      TRUE,  TRUE, 12, 20),
('WIN_BRUTE_SUCCESS',      'Windows brute force sėkmingas prisijungimas',                  TRUE,  TRUE, 12, 20),
('TPM_SNIFF',              'TPM magistralės klausymas BitLocker raktams',                  TRUE,  TRUE, 12, 30),

-- ── VIDUTINIAI — tik pranešimas, auto_isolate=FALSE ───────────────────────
('LATERAL_MOVEMENT',       'Šoninis judėjimas tinkle',                                     FALSE, TRUE, 10, 30),
('WINRM_LATERAL',          'WinRM lateral movement',                                        FALSE, TRUE, 10, 30),
('DCOM_LATERAL',           'DCOM lateral movement',                                         FALSE, TRUE, 10, 30),
('RDP_ABUSE',              'Neįprastas RDP naudojimas',                                    FALSE, TRUE, 10, 30),
('KERBEROASTING',          'Kerberoasting SPN harvesting',                                  FALSE, TRUE, 10, 30),
('AS_REP_ROASTING',        'AS-REP Roasting',                                               FALSE, TRUE, 10, 30),
('OVERPASS_THE_HASH',      'Overpass-the-Hash TGT',                                        FALSE, TRUE, 10, 30),
('KERBEROS_DELEGATION',    'Kerberos delegation abuse',                                     FALSE, TRUE, 10, 30),
('ADCS_ABUSE',             'ADCS sertifikatų piktnaudžiavimas',                            FALSE, TRUE, 10, 30),
('SHADOW_CREDENTIALS',     'Shadow Credentials msDS-KeyCredentialLink',                    FALSE, TRUE, 10, 30),
('NTLM_COERCION',          'NTLM coercion/relay',                                           FALSE, TRUE, 10, 30),
('DPAPI_ABUSE',            'DPAPI slaptų duomenų ištraukimas',                             FALSE, TRUE, 10, 30),
('LAPS_ABUSE',             'LAPS slaptažodžių skaitymas',                                  FALSE, TRUE, 10, 30),
('TOKEN_MANIPULATION',     'Token impersonation/theft',                                     FALSE, TRUE, 10, 30),
('PRIVESC_TOOLS',          'Privilege escalation tools',                                    FALSE, TRUE, 10, 30),
('WIN_ADMIN_GROUP_ADD',    'Vartotojas pridėtas į administratorius',                       FALSE, TRUE, 10, 30),
('WIN_USER_CREATED',       'Nauja vartotojo paskyra sukurta',                              FALSE, TRUE,  9, 30),
('USER_ACCOUNT_MANIP',     'Vartotojų paskyrų manipuliacija',                              FALSE, TRUE,  9, 30),
('GPO_ABUSE',              'GPO manipuliacija',                                             FALSE, TRUE, 10, 30),
('WSUS_ATTACK',            'WSUS ataka',                                                    FALSE, TRUE, 10, 30),
('PRINT_NIGHTMARE',        'PrintNightmare exploit',                                        FALSE, TRUE, 10, 30),
('AMSI_BYPASS',            'AMSI/ETW bypass',                                               FALSE, TRUE, 10, 30),
('REFLECTIVE_LOAD',        'Reflektyvus DLL/assembly load',                                FALSE, TRUE, 10, 30),
('ETW_PATCH',              'ETW/NT API patching',                                           FALSE, TRUE, 10, 30),
('PPID_SPOOF',             'Parent PID spoofing',                                           FALSE, TRUE,  9, 30),
('PROCESS_INJECTION',      'Process injection/hollowing',                                   FALSE, TRUE, 10, 30),
('PHANTOM_DLL_HOLLOW',     'Phantom DLL hollowing',                                        FALSE, TRUE, 10, 30),
('MEMORY_ONLY_STAGE',      'Fileless memory-only execution',                               FALSE, TRUE, 10, 30),
('DEFENSE_EVASION',        'Gynybos vengimas',                                              FALSE, TRUE,  9, 30),
('LOG_CLEARING',           'Įvykių žurnalų valymas',                                       FALSE, TRUE,  9, 30),
('WINDOWS_DEFENDER_EXCL',  'Windows Defender exclusion pridėjimas',                        FALSE, TRUE,  9, 30),
('ACCESSIBILITY_BACKDOOR', 'Sticky Keys/Utilman backdoor',                                 FALSE, TRUE, 10, 30),
('WMI_PERSISTENCE',        'WMI event subscription persistence',                           FALSE, TRUE,  9, 30),
('REGISTRY_DEEP_PERSISTENCE','Gilusis registro persistence',                               FALSE, TRUE,  9, 30),
('LSA_PROVIDER_PERSIST',   'LSA security package persistence',                             FALSE, TRUE, 10, 30),
('BITS_ABUSE',             'BITS persistence/download',                                    FALSE, TRUE,  8, 30),
('COM_HIJACK',             'COM object hijacking',                                          FALSE, TRUE,  8, 30),
('OFFICE_ADDIN_PERSIST',   'Office add-in persistence',                                    FALSE, TRUE,  8, 30),
('ACTIVE_SETUP_PERSIST',   'Active Setup persistence',                                     FALSE, TRUE,  8, 30),
('PERSISTENCE_SETUP',      'Bendrasis persistence',                                         FALSE, TRUE,  8, 30),
('STARTUP_PERSISTENCE',    'Startup katalogo persistence',                                FALSE, TRUE,  8, 30),
('LINUX_SSH_ABUSE',        'Linux SSH raktų vagystė/tuneliavimas',                         FALSE, TRUE,  8, 30),
('NETSH_HELPER_DLL',       'Netsh helper DLL persistence',                                 FALSE, TRUE,  8, 30),
('SCREENSAVER_PERSIST',    'Ekrano saugiklio persistence',                                 FALSE, TRUE,  6, 60),
('VDSO_INJECTION',         'Linux vDSO/vsyscall injekcija',                               FALSE, TRUE, 10, 30),
('AI_TOOL_ABUSE',          'AI įrankių piktnaudžiavimas',                                 FALSE, TRUE,  7, 60),
('LINUX_WEBSHELL',         'Linux web shell aptiktas',                                     FALSE, TRUE, 10, 20),
('LINUX_PRIVESC',          'Linux privilege escalation',                                   FALSE, TRUE,  9, 30),
('LOLBIN_EXEC',            'LOLBin download+execute',                                       FALSE, TRUE,  9, 30),
('LIVING_OFF_THE_LAND_PS', 'PowerShell LOLBin chain',                                      FALSE, TRUE,  9, 30),
('APPLOCKER_BYPASS',       'AppLocker bypass',                                              FALSE, TRUE,  8, 30),
('DLL_SIDELOAD',           'DLL sideloading',                                               FALSE, TRUE,  8, 30),
('MASQUERADE_PROC',        'Proceso vardo maskavimas',                                     FALSE, TRUE,  9, 30),
('OBFUSCATION_INDICATORS', 'Kodo obfuskacija',                                             FALSE, TRUE,  8, 30),
('DATA_EXFIL',             'Duomenų išfiltravimas',                                         FALSE, TRUE, 10, 30),
('DNS_EXFIL',              'DNS tuneliavimas',                                              FALSE, TRUE,  9, 30),
('TUNNELING',              'Tinklo tuneliavimas',                                           FALSE, TRUE,  9, 30),
('TOR_I2P_USAGE',          'Tor/I2P naudojimas',                                            FALSE, TRUE,  8, 30),
('ICMP_COVERT',            'ICMP covert channel',                                           FALSE, TRUE,  8, 30),
('PROXY_MULTIHOP',         'Multi-hop proxy grandinė',                                     FALSE, TRUE,  8, 30),
('PORT_FORWARD',           'Port forwarding',                                               FALSE, TRUE,  7, 30),
('NETWORK_C2_BEACON',      'C2 beacon aptiktas',                                           FALSE, TRUE, 10, 20),
('NETWORK_PORT_SCAN',      'Port scan aptiktas',                                            FALSE, TRUE,  7, 60),
('LLMNR_POISONING',        'LLMNR/NBT-NS apnuodijimas',                                   FALSE, TRUE,  8, 30),
('AD_RECON',               'Active Directory žvalgyba',                                     FALSE, TRUE,  8, 30),
('CLOUD_RECON',            'Cloud infrastruktūros žvalgyba',                               FALSE, TRUE,  8, 30),
('RECON_CHAIN',            'Žvalgybos komandų grandinė',                                   FALSE, TRUE,  7, 60),
('LINUX_RECON',            'Linux sistemos žvalgyba',                                       FALSE, TRUE,  7, 60),
('LINUX_PERSISTENCE',      'Linux persistence',                                             FALSE, TRUE,  8, 30),
('LINUX_CRED_DUMP',        'Linux kredencialų ištraukimas',                                FALSE, TRUE,  9, 30),
('LINUX_LD_PRELOAD',       'LD_PRELOAD injekcija',                                         FALSE, TRUE,  9, 30),
('LINUX_CAPABILITY_ABUSE', 'Linux capabilities abuse',                                     FALSE, TRUE,  9, 30),
('LINUX_PROC_INJECTION',   'Linux ptrace/proc injekcija',                                  FALSE, TRUE,  9, 30),
('LINUX_MEMFD_EXEC',       'Linux fileless ataka',                                          FALSE, TRUE, 10, 30),
('LINUX_SSH_BRUTE',        'SSH brute force bandymas',                                     FALSE, TRUE,  7, 60),
('CRON_DOWNLOAD_EXEC',     'Cron download+exec',                                            FALSE, TRUE,  9, 30),
('WIN_RECON_CHAIN',        'Windows žvalgybos grandinė',                                   FALSE, TRUE,  7, 60),
('WIN_CREDENTIAL_TOOL',    'Kredencialų įrankis aptiktas',                                 FALSE, TRUE, 10, 20),
('WIN_LATERAL_MOVEMENT',   'Windows lateral movement',                                     FALSE, TRUE, 10, 20),
('WIN_MACRO_SHELL',        'Office macro→shell',                                            FALSE, TRUE, 10, 20),
('WIN_SCHEDULED_TASK',     'Scheduled task sukurta',                                       FALSE, TRUE,  8, 30),
('WIN_SERVICE_INSTALL',    'Windows service įdiegta',                                      FALSE, TRUE,  8, 30),
('WIN_TIMESTOMPING',       'File timestomping',                                             FALSE, TRUE,  8, 30),
('WIN_BRUTE_ATTEMPT',      'Windows brute force bandymas',                                 FALSE, TRUE,  6, 60),
('VULNERABILITY_CRITICAL', 'Critical CVE pažeidžiamumas',                                  FALSE, TRUE,  8, 120),
('OFFICE_MACRO_CHAIN',     'Office macro vykdymo grandinė',                                FALSE, TRUE,  9, 30),
('ISO_LNK_EXEC',           'ISO/LNK failo vykdymas',                                       FALSE, TRUE,  8, 30),
('HTML_SMUGGLING',         'HTML smuggling',                                                FALSE, TRUE,  8, 30),
('CHM_SCRIPTLET',          'CHM/Scriptlet vykdymas',                                       FALSE, TRUE,  8, 30),
('CREDENTIAL_FILE_ACCESS', 'Credential failų prieiga',                                     FALSE, TRUE,  8, 30),
('BROWSER_CRED_THEFT',     'Naršyklių kredencialai',                                       FALSE, TRUE,  9, 30),
('KEYLOGGING',             'Klaviatūros sekimas',                                           FALSE, TRUE,  9, 30),
('NETWORK_SNIFF',          'Tinklo srauto klausymas',                                      FALSE, TRUE,  7, 60),
('SCREEN_CAPTURE',         'Ekrano/klaviatūros rinkimas',                                  FALSE, TRUE,  7, 60),
('EMAIL_COLLECTION',       'El. pašto duomenų rinkimas',                                   FALSE, TRUE,  8, 30),
('SHARE_ENUM_COLLECTION',  'Tinklo diskų išvardijimas',                                    FALSE, TRUE,  6, 60),
('RMM_ABUSE',              'RMM įrankio piktnaudžiavimas',                                 FALSE, TRUE,  8, 30),
('SUPPLY_CHAIN_INDICATORS','Tiekimo grandinės ataka',                                       FALSE, TRUE,  9, 30),
('CONTAINER_ESCAPE',       'Konteinerio izoliacija pažeista',                              FALSE, TRUE, 10, 30),
('MFA_BYPASS',             'MFA aplenkimas',                                                FALSE, TRUE, 10, 30),
('MFA_FATIGUE_ADVANCED',   'MFA fatigue ataka',                                            FALSE, TRUE,  9, 30),
('WINDOWS_HELLO_BYPASS',   'Windows Hello bypass',                                          FALSE, TRUE, 10, 30),
('OAUTH_ABUSE',            'OAuth piktnaudžiavimas',                                        FALSE, TRUE,  9, 30),
('O365_TOKEN_THEFT',       'O365 token vagystė',                                            FALSE, TRUE, 10, 30),
('AZURE_ABUSE',            'Azure AD piktnaudžiavimas',                                    FALSE, TRUE, 10, 30),
('AWS_ABUSE',              'AWS IAM piktnaudžiavimas',                                     FALSE, TRUE, 10, 30),
('IMDS_ABUSE',             'Cloud IMDS metadata abuse',                                    FALSE, TRUE,  9, 30),
('SaaS_LATERAL',           'SaaS lateral movement',                                         FALSE, TRUE,  9, 30),
('AZURE_ARC_ABUSE',        'Azure Arc agent abuse',                                         FALSE, TRUE, 10, 30),
('POWER_PLATFORM_ABUSE',   'Power Platform/Automate abuse',                                FALSE, TRUE,  8, 30),
('MICROSOFT_TEAMS_PHISH',  'Teams phishing',                                                FALSE, TRUE,  8, 30),
('NHI_CREDENTIAL_ABUSE',   'Non-Human Identity abuse',                                     FALSE, TRUE,  9, 30),
('SLOPSQUATTING',          'AI paketo pavadinimų apgaulė',                                 FALSE, TRUE,  8, 30),
('AI_AGENT_COMPROMISE',    'AI agento kompromitavimas',                                    FALSE, TRUE,  9, 30),
('PROMPT_INJECTION_RCE',   'Prompt injection→RCE',                                         FALSE, TRUE,  9, 30),
('DEEPFAKE_VISHING',       'Deepfake vishing/BEC',                                         FALSE, TRUE,  7, 60),
('QUISHING',               'QR phishing',                                                   FALSE, TRUE,  6, 60),
('RUST_GO_MALWARE',        'Rust/Go malware loader',                                        FALSE, TRUE,  8, 30),
('GITHUB_ACTIONS_ABUSE',   'CI/CD pipeline abuse',                                          FALSE, TRUE,  8, 30),
('ICS_OT_RECON',           'ICS/SCADA žvalgyba',                                           FALSE, TRUE,  8, 30),
('CRYPTOMINING',           'Kriptovaliutų kasimas',                                         FALSE, TRUE,  7, 60),
('WIFI_ATTACK',            'Wi-Fi ataka',                                                   FALSE, TRUE,  7, 60),
('SCATTERED_SPIDER_TTP',   'Scattered Spider TTP',                                          FALSE, TRUE, 10, 30),
('VOLT_TYPHOON_TTP',       'Volt Typhoon TTP',                                              FALSE, TRUE, 10, 30),
('BLACKCAT_ALPHV_TTP',     'BlackCat/ALPHV TTP',                                           FALSE, TRUE, 11, 10),
('LAZARUS_TTP',            'Lazarus Group TTP',                                             FALSE, TRUE, 10, 30),
('HNDL_COLLECTION',        'Harvest Now Decrypt Later',                                    FALSE, TRUE,  7, 60),
('LIVING_OFF_TRUSTED_SITES','LOTS C2 per patikimas svetaines',                             FALSE, TRUE,  8, 30),
('SEO_POISONING_EXEC',     'SEO poisoning vykdymo grandinė',                               FALSE, TRUE,  7, 30),
('PASSWORD_POLICY_ENUM',   'Slaptažodžių politikos žvalgyba',                              FALSE, TRUE,  5, 60),
('SECURITY_TOOL_ENUM',     'AV/EDR įrankių išvardijimas',                                  FALSE, TRUE,  5, 60),
('VM_SANDBOX_DETECT',      'VM/sandbox aplinkos aptikimas',                                FALSE, TRUE,  5, 60),
('INTERNAL_SPEARPHISH',    'Vidinis spearphishing',                                         FALSE, TRUE,  8, 30),
('NTFS_ADS',               'NTFS Alternate Data Streams',                                   FALSE, TRUE,  7, 60),
('TIMESTOMPING',           'Failo laiko keitimas',                                          FALSE, TRUE,  6, 60)

ON CONFLICT (trigger_type) DO NOTHING;